# yes24 검색어 검색 결과
- 국내도서 x 검색어
- 책제목, 가격(정수), 상세페이지url, 썸네일이미지url
- 페이징
- 썸네일 이미지 다운로드 --> 상품 아이디 명으로 다운로드 받기

In [1]:
"""
[{'thumbnail_url': 'http://image.yes24.com/Goods/74419916/L',
  'book_title': 'Do it! 점프 투 파이썬',
  'book_url': 'http://www.yes24.com/Product/Goods/74419916?OzSrank=1',
  'price': 16920},
 {'thumbnail_url': 'http://image.yes24.com/Goods/74269975/L',
  'book_title': '혼자 공부하는 파이썬',
  'book_url': 'http://www.yes24.com/Product/Goods/74269975?OzSrank=2',
  'price': 16200},
 {'thumbnail_url': 'http://image.yes24.com/Goods/96024871/L',
  'book_title': '혼자 공부하는 머신러닝+딥러닝',
  'book_url': 'http://www.yes24.com/Product/Goods/96024871?OzSrank=3',
  'price': 23400},
  ...
]
"""
None

# import

In [2]:
import requests
from bs4 import BeautifulSoup

import urllib
import urllib.parse as urlparser  # 파일명 분리를 위해 필요
import os
import re
from pprint import pprint

In [5]:
keyword = "파이썬"
url = f"https://www.yes24.com/product/search?domain=BOOK&query={keyword}&page=1&size=24"
url

'https://www.yes24.com/product/search?domain=BOOK&query=파이썬&page=1&size=24'

In [7]:
response = requests.get(url)
response

In [9]:
response.status_code

200

In [11]:
response.text[:100] # 응답 받은  HTML 텍스트

'\r\n\r\n\r\n\r\n\r\n    \r\n\t<!DOCTYPE html >\r\n\t<html lang="ko">\r\n\r\n<head>\r\n\t<meta http-equiv="X-UA-Compatible" '

In [13]:
soup = BeautifulSoup(response.text, 'html.parser')

In [14]:
# 검색 결과 목록
book_list = soup.select("#yesSchList > li")

len(book_list)

24

# 썸네일 이미지

In [17]:
# 첫번째 항목
book_item = book_list[0]

In [18]:
book_item.select_one("div.item_img > div.img_canvas > span > span > a > em > img")

In [19]:
# 위에서 실제 이미지 url 은 data-original 속성에 담겨 있더라.

In [20]:
book_item.select_one("div.item_img > div.img_canvas > span > span > a > em > img").attrs['data-original'].strip()

'https://image.yes24.com/goods/119293186/L'

In [21]:
for book_item in book_list:
    img_src = book_item.select_one("div.item_img > div.img_canvas > span > span > a > em > img").attrs['data-original'].strip()
    print(img_src)

https://image.yes24.com/goods/119293186/L
https://image.yes24.com/goods/109625396/L
https://image.yes24.com/goods/190216677/L
https://image.yes24.com/goods/191208982/L
https://image.yes24.com/goods/187024885/L
https://image.yes24.com/goods/148027839/L
https://image.yes24.com/goods/185160480/L
https://image.yes24.com/goods/117373102/L
https://image.yes24.com/goods/183530330/L
https://image.yes24.com/goods/189353153/L
https://image.yes24.com/goods/116253011/L
https://image.yes24.com/goods/180386822/L
https://image.yes24.com/goods/130326801/L
https://image.yes24.com/goods/143533211/L
https://image.yes24.com/goods/167430900/L
https://image.yes24.com/goods/118523424/L
https://image.yes24.com/goods/124832401/L
https://image.yes24.com/goods/104405577/L
https://image.yes24.com/goods/116038106/L
https://image.yes24.com/goods/141787639/L
https://image.yes24.com/goods/167459219/L
https://image.yes24.com/goods/91219874/L
https://image.yes24.com/goods/142258696/L
https://image.yes24.com/goods/140126422/L

In [22]:
for book_item in book_list:
    img_src = book_item.select_one("div.item_img img").attrs['data-original'].strip()
    print(img_src)

https://image.yes24.com/goods/119293186/L
https://image.yes24.com/goods/109625396/L
https://image.yes24.com/goods/190216677/L
https://image.yes24.com/goods/191208982/L
https://image.yes24.com/goods/187024885/L
https://image.yes24.com/goods/148027839/L
https://image.yes24.com/goods/185160480/L
https://image.yes24.com/goods/117373102/L
https://image.yes24.com/goods/183530330/L
https://image.yes24.com/goods/189353153/L
https://image.yes24.com/goods/116253011/L
https://image.yes24.com/goods/180386822/L
https://image.yes24.com/goods/130326801/L
https://image.yes24.com/goods/143533211/L
https://image.yes24.com/goods/167430900/L
https://image.yes24.com/goods/118523424/L
https://image.yes24.com/goods/124832401/L
https://image.yes24.com/goods/104405577/L
https://image.yes24.com/goods/116038106/L
https://image.yes24.com/goods/141787639/L
https://image.yes24.com/goods/167459219/L
https://image.yes24.com/goods/91219874/L
https://image.yes24.com/goods/142258696/L
https://image.yes24.com/goods/140126422/L

# 책제목

In [24]:
for book_item in book_list:
    book_title = book_item.select_one("div.item_info a.gd_name").text.strip()
    print(book_title)

Do it! 점프 투 파이썬
혼자 공부하는 파이썬
데이터 과학을 위한 기초수학 with 파이썬
파이썬의 도구들
요즘 바이브 코딩 커서 X 클로드 코드 실전 외주 돈 벌기
Do it! 점프 투 파이썬 + Do it! LLM을 활용한 AI 에이전트 개발 입문 세트
2026 시나공 빅데이터분석기사 실기 Python
코딩 자율학습 나도코딩의 파이썬 입문
바로바로 바이브 코딩 with 커서 AI
코딩 자율학습 FastAPI 파이썬 백엔드 개발 입문
혼자 공부하는 데이터 분석 with 파이썬
이펙티브 파이썬
자기주도 파이썬
선생님을 위한 8282 업무 자동화 with AI+파이썬+노코드
파이썬으로 시작하는 인공지능 기초 수업
파이썬 라이브러리를 활용한 데이터 분석
수학자와 함께하는 인공지능 수학 with 파이썬
그림으로 배우는 파이썬
Do it! 게임 10개 만들며 배우는 파이썬
밑바닥부터 시작하는 딥러닝 1
파이썬만으로 시작하는 1인 게임 개발
Do it! 자료구조와 함께 배우는 알고리즘 입문 : 파이썬 편
혼자 만들면서 공부하는 파이썬
쑥쑥 팡팡 코딩활용능력 1급(파이썬)

# 책 상세정보 페이지 URL

In [33]:
for book_item in book_list:
    book_url = "https://www.yes24.com" + book_item.select_one("div.item_info a.gd_name").attrs['href'].strip()
    print(book_url)

https://www.yes24.com/product/goods/119293186
https://www.yes24.com/product/goods/109625396
https://www.yes24.com/product/goods/190216677
https://www.yes24.com/product/goods/191208982
https://www.yes24.com/product/goods/187024885
https://www.yes24.com/product/goods/148027839
https://www.yes24.com/product/goods/185160480
https://www.yes24.com/product/goods/117373102
https://www.yes24.com/product/goods/183530330
https://www.yes24.com/product/goods/189353153
https://www.yes24.com/product/goods/116253011
https://www.yes24.com/product/goods/180386822
https://www.yes24.com/product/goods/130326801
https://www.yes24.com/product/goods/143533211
https://www.yes24.com/product/goods/167430900
https://www.yes24.com/product/goods/118523424
https://www.yes24.com/product/goods/124832401
https://www.yes24.com/product/goods/104405577
https://www.yes24.com/product/goods/116038106
https://www.yes24.com/product/goods/141787639
https://www.yes24.com/product/goods/167459219
https://www.yes24.com/product/goods/91219874
https://www.yes24.com/product/goods/142258696
https://www.yes24.com/product/goods/140126422

# 가격

In [34]:
for book_item in book_list:
    price = book_item.select_one("div.item_info > div.info_price > strong > em").text.strip()
    print(price)

19,800
19,800
28,000
21,600
23,400
51,300
28,800
21,600
27,000
25,200
23,400
37,800
18,000
25,200
22,500
35,100
32,000
16,200
19,800
23,400
19,800
19,800
23,400
19,800

# 종합: 함수로 정의

In [36]:
def crawl_yes24(query, page=1):
    print(f'🔶 {query} 검색 page{page}...')

    url = f'https://www.yes24.com/product/search?domain=BOOK&query={query}&page={page}&size=24'

    response = requests.get(url)
    if response.status_code != 200: return

    dom = BeautifulSoup(response.text, 'html.parser')
    book_list = dom.select('#yesSchList > li')

    result = []

    for book_item in book_list:
        # 썸네일
        img_src = book_item.select_one("div.item_img > div.img_canvas > span > span > a > em > img").attrs['data-original'].strip()
    
        # 책제목
        book_title = book_item.select_one("div.item_info a.gd_name").text.strip()
    
        # 책URL
        book_url = 'https://www.yes24.com' + book_item.select_one("div.item_info a.gd_name").attrs['href'].strip()
    
        # 가격
        price = book_item.select_one("div.item_info > div.info_row.info_price > strong > em").text.strip()
        price = int(re.sub('[^0-9]', '', price))

        result.append({
            'thumbnail_url': img_src,
            'book_title': book_title,
            'book_url': book_url,
            "price": price,
        })

    return result

In [39]:
result = crawl_yes24('파이썬', 3)
result

🔶 파이썬 검색 page3...

[{'thumbnail_url': 'https://image.yes24.com/goods/123272392/L',
  'book_title': '코딩 테스트 합격자 되기 - 파이썬 편',
  'book_url': 'https://www.yes24.com/product/goods/123272392',
  'price': 36000},
 {'thumbnail_url': 'https://image.yes24.com/goods/106175772/L',
  'book_title': '웹 크롤링 & 데이터 분석 with 파이썬',
  'book_url': 'https://www.yes24.com/product/goods/106175772',
  'price': 18000},
 {'thumbnail_url': 'https://image.yes24.com/goods/128218982/L',
  'book_title': '파이썬 + AI',
  'book_url': 'https://www.yes24.com/product/goods/128218982',
  'price': 25200},
 {'thumbnail_url': 'https://image.yes24.com/goods/147129792/L',
  'book_title': '처음이야? 파이썬 데이터 분석',
  'book_url': 'https://www.yes24.com/product/goods/147129792',
  'price': 19800},
 {'thumbnail_url': 'https://image.yes24.com/goods/149224228/L',
  'book_title': '모두의 인공지능 with 파이썬',
  'book_url': 'https://www.yes24.com/product/goods/149224228',
  'price': 27000},
 {'thumbnail_url': 'https://image.yes24.com/goods/136469562/L',
  'book_title': '파이썬 데이터 분석가 되기+챗GPT',
  'book_url': 'https://www.yes24.com/product/goods/136469562',
  'price': 23400},
 {'thumbnail_url': 'https://image.yes24.com/goods/116038054/L',
  'book_title': '시간순삭 파이썬',
  'book_url': 'https://www.yes24.com/product/goods/116038054',
  'price': 22500},
 {'thumbnail_url': 'https://image.yes24.com/goods/140256885/L',
  'book_title': '파이썬 업무 자동화 일잘러 되기 + 챗GPT',
  'book_url': 'https://www.yes24.com/product/goods/140256885',
  'price': 32400},
 {'thumbnail_url': 'https://image.yes24.com/goods/128897247/L',
  'book_title': '파이썬 코딩의 기술 51 Better Python Code',
  'book_url': 'https://www.yes24.com/product/goods/128897247',
  'price': 29700},
 {'thumbnail_url': 'https://image.yes24.com/goods/118396923/L',
  'book_title': 'IT 비전공자를 위한 파이썬 업무 자동화 (RPA)',
  'book_url': 'https://www.yes24.com/product/goods/118396923',
  'price': 23400},
 {'thumbnail_url': 'https://image.yes24.com/goods/119117002/L',
  'book_title': '모두의 한국어 텍스트 분석 with 파이썬',
  'book_url': 'https://www.yes24.com/product/goods/119117002',
  'price': 24300},
 {'thumbnail_url': 'https://image.yes24.com/goods/170374556/L',
  'book_title': 'LUVIT♥ 파이썬으로 만드는 초경량 한국어 LLM 챗봇',
  'book_url': 'https://www.yes24.com/product/goods/170374556',
  'price': 25200},
 {'thumbnail_url': 'https://image.yes24.com/goods/129111891/L',
  'book_title': '25가지 문제로 배우는 LLM 입문 with 파이썬',
  'book_url': 'https://www.yes24.com/product/goods/129111891',
  'price': 25200},
 {'thumbnail_url': 'https://image.yes24.com/goods/127925147/L',
  'book_title': '커리어 스킬업 파이썬 업무 자동화',
  'book_url': 'https://www.yes24.com/product/goods/127925147',
  'price': 23400},
 {'thumbnail_url': 'https://image.yes24.com/goods/110141162/L',
  'book_title': '파이썬 객체지향 프로그래밍 4/e',
  'book_url': 'https://www.yes24.com/product/goods/110141162',
  'price': 38700},
 {'thumbnail_url': 'https://image.yes24.com/goods/76899516/L',
  'book_title': '암호 해킹으로 배우는 파이썬의 기초',
  'book_url': 'https://www.yes24.com/product/goods/76899516',
  'price': 31500},
 {'thumbnail_url': 'https://image.yes24.com/goods/140199863/L',
  'book_title': '파이썬으로 배우는 확률과 통계',
  'book_url': 'https://www.yes24.com/product/goods/140199863',
  'price': 36000},
 {'thumbnail_url': 'https://image.yes24.com/goods/104102229/L',
  'book_title': '쉽게 따라 만드는 파이썬 주식 자동매매 시스템',
  'book_url': 'https://www.yes24.com/product/goods/104102229',
  'price': 25200},
 {'thumbnail_url': 'https://image.yes24.com/goods/101921911/L',
  'book_title': '파이썬 해킹 레시피',
  'book_url': 'https://www.yes24.com/product/goods/101921911',
  'price': 23400},
 {'thumbnail_url': 'https://image.yes24.com/goods/115096537/L',
  'book_title': '파이썬 웹 프로그래밍, 기초편',
  'book_url': 'https://www.yes24.com/product/goods/115096537',
  'price': 23400},
 {'thumbnail_url': 'https://image.yes24.com/goods/118796944/L',
  'book_title': '제대로 빠르게 파이썬 입문',
  'book_url': 'https://www.yes24.com/product/goods/118796944',
  'price': 26820},
 {'thumbnail_url': 'https://image.yes24.com/goods/124732783/L',
  'book_title': '파이썬 데이터 분석 & 시각화 + 웹 대시보드 제작하기',
  'book_url': 'https://www.yes24.com/product/goods/124732783',
  'price': 15930},
 {'thumbnail_url': 'https://image.yes24.com/goods/128592953/L',
  'book_title': '10대를 위한 데이터과학 with 파이썬',
  'book_url': 'https://www.yes24.com/product/goods/128592953',
  'price': 24300},
 {'thumbnail_url': 'https://image.yes24.com/goods/110242564/L',
  'book_title': '통계학 : 파이썬을 이용한 분석',
  'book_url': 'https://www.yes24.com/product/goods/110242564',
  'price': 32000}]

In [38]:
import pandas as pd

In [40]:
df = pd.DataFrame(result)
df

,thumbnail_url,book_title,book_url,price
0,https://image.yes24.com/goods/123272392/L,코딩 테스트 합격자 되기 - 파이썬 편,https://www.yes24.com/product/goods/123272392,36000
1,https://image.yes24.com/goods/106175772/L,웹 크롤링 & 데이터 분석 with 파이썬,https://www.yes24.com/product/goods/106175772,18000
2,https://image.yes24.com/goods/128218982/L,파이썬 + AI,https://www.yes24.com/product/goods/128218982,25200
3,https://image.yes24.com/goods/147129792/L,처음이야? 파이썬 데이터 분석,https://www.yes24.com/product/goods/147129792,19800
4,https://image.yes24.com/goods/149224228/L,모두의 인공지능 with 파이썬,https://www.yes24.com/product/goods/149224228,27000
5,https://image.yes24.com/goods/136469562/L,파이썬 데이터 분석가 되기+챗GPT,https://www.yes24.com/product/goods/136469562,23400
6,https://image.yes24.com/goods/116038054/L,시간순삭 파이썬,https://www.yes24.com/product/goods/116038054,22500
7,https://image.yes24.com/goods/140256885/L,파이썬 업무 자동화 일잘러 되기 + 챗GPT,https://www.yes24.com/product/goods/140256885,32400
8,https://image.yes24.com/goods/128897247/L,파이썬 코딩의 기술 51 Better Python Code,https://www.yes24.com/product/goods/128897247,29700
9,https://image.yes24.com/goods/118396923/L,IT 비전공자를 위한 파이썬 업무 자동화 (RPA),https://www.yes24.com/product/goods/118396923,23400
10,https://image.yes24.com/goods/119117002/L,모두의 한국어 텍스트 분석 with 파이썬,https://www.yes24.com/product/goods/119117002,24300
11,https://image.yes24.com/goods/170374556/L,LUVIT♥ 파이썬으로 만드는 초경량 한국어 LLM 챗봇,https://www.yes24.com/product/goods/170374556,25200
12,https://image.yes24.com/goods/129111891/L,25가지 문제로 배우는 LLM 입문 with 파이썬,https://www.yes24.com/product/goods/129111891,25200
13,https://image.yes24.com/goods/127925147/L,커리어 스킬업 파이썬 업무 자동화,https://www.yes24.com/product/goods/127925147,23400
14,https://image.yes24.com/goods/110141162/L,파이썬 객체지향 프로그래밍 4/e,https://www.yes24.com/product/goods/110141162,38700
15,https://image.yes24.com/goods/76899516/L,암호 해킹으로 배우는 파이썬의 기초,https://www.yes24.com/product/goods/76899516,31500
16,https://image.yes24.com/goods/140199863/L,파이썬으로 배우는 확률과 통계,https://www.yes24.com/product/goods/140199863,36000
17,https://image.yes24.com/goods/104102229/L,쉽게 따라 만드는 파이썬 주식 자동매매 시스템,https://www.yes24.com/product/goods/104102229,25200
18,https://image.yes24.com/goods/101921911/L,파이썬 해킹 레시피,https://www.yes24.com/product/goods/101921911,23400
19,https://image.yes24.com/goods/115096537/L,"파이썬 웹 프로그래밍, 기초편",https://www.yes24.com/product/goods/115096537,23400
20,https://image.yes24.com/goods/118796944/L,제대로 빠르게 파이썬 입문,https://www.yes24.com/product/goods/118796944,26820
21,https://image.yes24.com/goods/124732783/L,파이썬 데이터 분석 & 시각화 + 웹 대시보드 제작하기,https://www.yes24.com/product/goods/124732783,15930
22,https://image.yes24.com/goods/128592953/L,10대를 위한 데이터과학 with 파이썬,https://www.yes24.com/product/goods/128592953,24300
23,https://image.yes24.com/goods/110242564/L,통계학 : 파이썬을 이용한 분석,https://www.yes24.com/product/goods/110242564,32000

# 엑셀 저장하기

In [41]:
out_path = os.path.join('out', 'yes24')
if not os.path.exists(out_path):
    os.makedirs(out_path)
    print(out_path, '디렉토리 생성')

out/yes24 디렉토리 생성

In [42]:
csv_path = os.path.join(out_path, f"파이썬_page2.csv")

df.to_csv(csv_path, encoding='utf8')

# 페이징

In [43]:
query = '김정준'

In [45]:
result = []

for page in range(1,4):
    page_result = crawl_yes24(query, page)

    if not page_result: break

    result += page_result

pd.DataFrame(result)

🔶 김정준 검색 page1...
🔶 김정준 검색 page2...
🔶 김정준 검색 page3...

,thumbnail_url,book_title,book_url,price
0,https://image.yes24.com/goods/177078745/L,2026 시나공 정보처리기사 실기 기본서,https://www.yes24.com/product/goods/177078745,36000
1,https://image.yes24.com/goods/159574278/L,2026 시나공 정보처리기사 필기 기본서,https://www.yes24.com/product/goods/159574278,31500
2,https://image.yes24.com/goods/177078744/L,2026 시나공 정보처리산업기사 실기 기본서,https://www.yes24.com/product/goods/177078744,29700
3,https://image.yes24.com/goods/159575323/L,2026 시나공 정보처리산업기사 필기 기본서,https://www.yes24.com/product/goods/159575323,27000
4,https://image.yes24.com/goods/167580230/L,엘리트 코스를 밟은 성악가 김정준,https://www.yes24.com/product/goods/167580230,10800
...,...,...,...,...
67,https://image.yes24.com/goods/97648303/L,2021 시나공 정보처리기사 실기,https://www.yes24.com/product/goods/97648303,29700
68,https://image.yes24.com/goods/69236682/L,2019 시나공 정보처리기사 실기 (산업기사 포함),https://www.yes24.com/product/goods/69236682,27900
69,https://image.yes24.com/goods/96706474/L,2021 시나공 정보처리기사 필기,https://www.yes24.com/product/goods/96706474,29700
70,https://image.yes24.com/goods/96657522/L,2021 시나공 정보처리산업기사 실기,https://www.yes24.com/product/goods/96657522,27900
71,https://image.yes24.com/goods/108017355/L,2022 시나공 정보처리산업기사 실기,https://www.yes24.com/product/goods/108017355,27000