<img src = "https://i.imgur.com/r0YE5Xs.png"><br>
한국 주식 가격, 미국주식 가격, 지수, 환율, 암호화폐 가격, 종목 리스팅 등 금융 데이터 수집 라이브러리<br><br>
    
# FinanceDataReader 
Github  https://github.com/FinanceData/FinanceDataReader  <br>
FaceBook https://www.facebook.com/financedata  <br>
최신 업뎃 (0.7.1) (2018현재) node   https://github.com/FinanceData/FinanceDataReader/wiki/Release-Note-0.7.1?fbclid=IwAR0copSbDQiaZu-p44ntPqu9KK_GA5BLgm-DCj7VCNiX_QDX3ZxTniXQHcI <br>

UserGuide https://github.com/FinanceData/FinanceDataReader/wiki/Users-Guide <br>
symbol https://github.com/FinanceData/FinanceDataReader/wiki/Quick-Reference <br>

## Overview

FinanceDataReader 는 과거의 pandas-datareader 를 대체하기 위해 제작됨.  주요 특징은 아래와 같다

<ul>
    <li>Stock price(Word wide): AAPL, AMZN, GOOG ...   (종목별 주가: 세계)</li>
    <li>Stock price(KRX): 005930(Samsung), 091990(Celltrion Healthcare) ... (종목별주가: 한국)</li>
    <li>Indexes: KOSPI, KOSDAQ, DJI, IXIC, US500(S&P 500) ... (주요 지수들)</li>
    <li>Exchanges: USD/KRX, USD/EUR, CNY/KRW ... (환율)</li>
    <li>Cryptocurrency: BTC/USD (Bitfinex), BTC/KRW (Bithumb)  (가상화폐)</li>
    <li>Symbol listings: KRX (KOSPI, KODAQ, KONEX), NASDAQ, NYSE, AMEX and S&P 500 ( ???? )</li>
</ul>

In [1]:
import FinanceDataReader as fdr

In [10]:
df = fdr.DataReader('AAPL', '2026-08-01')
df

,Open,High,Low,Close,Volume,Adj Close
2026-07-31,304.809998,310.690002,300.000000,308.910004,132489100,308.643829
2026-08-03,309.579987,311.799988,302.559998,303.420013,75052000,303.158569
2026-08-04,302.730011,310.420013,301.320007,309.380005,68001000,309.113403
2026-08-05,309.359985,311.709991,305.670013,311.000000,49438800,310.732025
2026-08-06,314.339996,316.290009,309.230011,312.410004,46139900,312.140808
2026-08-07,311.450012,314.809998,310.739990,313.329987,34437200,313.059998
2026-08-10,306.829987,308.260010,304.609985,308.260010,44812500,308.260010
2026-08-11,307.750000,309.970001,302.790009,304.910004,37476700,304.910004
2026-08-12,305.100006,305.660004,300.570007,302.250000,41657800,302.250000
2026-08-13,304.257996,306.000000,302.049988,305.260010,38492546,305.260010

In [7]:
df = fdr.DataReader('AMZN', '2026-07-02', '2026-07-31')
df

,Open,High,Low,Close,Volume,Adj Close
2026-07-01,239.750000,244.899994,234.899994,241.699997,53829900,241.699997
2026-07-02,241.610001,246.720001,241.080002,242.669998,48246400,242.669998
2026-07-06,243.800003,246.039993,240.880005,244.160004,40044000,244.160004
2026-07-07,246.979996,248.929993,242.699997,245.979996,40579600,245.979996
2026-07-08,244.270004,244.800003,240.520004,243.619995,29653000,243.619995
2026-07-09,239.820007,247.500000,238.250000,247.039993,38091700,247.039993
2026-07-10,249.550003,251.029999,244.410004,245.339996,31654000,245.339996
2026-07-13,244.679993,249.649994,244.179993,247.309998,34636100,247.309998
2026-07-14,245.550003,248.559998,243.800003,247.490005,30108100,247.490005
2026-07-15,249.750000,256.480011,249.750000,254.960007,45240600,254.960007
2026-07-16,255.119995,258.079987,248.000000,249.889999,45343700,249.889999
2026-07-17,244.460007,250.240005,243.589996,247.229996,43572400,247.229996
2026-07-20,248.759995,252.889999,248.000000,249.990005,32406500,249.990005
2026-07-21,249.110001,249.339996,246.419998,247.550003,27732100,247.550003
2026-07-22,248.270004,248.449997,242.449997,244.850006,34112700,244.850006
2026-07-23,236.259995,238.350006,232.050003,233.660004,47465300,233.660004
2026-07-24,234.380005,234.949997,231.339996,232.110001,35017400,232.110001
2026-07-27,235.669998,235.889999,230.990005,231.389999,34999500,231.389999
2026-07-28,232.850006,233.110001,228.100006,230.860001,44521600,230.860001
2026-07-29,229.320007,232.820007,226.160004,226.649994,44957500,226.649994
2026-07-30,233.350006,239.820007,231.059998,235.500000,101839800,235.500000

In [6]:
df = fdr.DataReader('005930', '2026-07-01', '2026-08-01')
df

              Open    High     Low   Close    Volume    Change
Date
2026-07-01  334500  339000  311500  314500  24968382 -0.058383
2026-07-02  290000  304000  281500  286000  38905074 -0.090620
2026-07-03  288500  313000  283500  309500  31520538  0.082168
2026-07-06  320000  325000  303000  318000  23872879  0.027464
2026-07-07  307000  310000  286000  296000  32421032 -0.069182
2026-07-08  285500  300000  273500  277500  33525758 -0.062500
2026-07-09  288500  291500  267500  278000  29703616  0.001802
2026-07-10  291000  298000  282000  285000  20088811  0.025180
2026-07-13  285000  292500  253000  254500  31882652 -0.107018
2026-07-14  255000  270000  247000  263000  40086496  0.033399
2026-07-15  283500  284500  273000  279500  24873414  0.062738
2026-07-16  264500  265500  252500  255000  27001478 -0.087657
2026-07-20  241000  257500  240000  244000  26804038 -0.043137
2026-07-21  247000  263500  243000  259000  20386896  0.061475
2026-07-22  276000  276000  260000  260500  22292003  0.005792
2026-07-23  269000  273000  263000  270000  16011816  0.036468
2026-07-24  266000  266500  247000  249500  26175580 -0.075926
2026-07-27  257000  258500  246000  254000  23296044  0.018036
2026-07-28  238500  240000  218500  220000  41639623 -0.133858
2026-07-29  226500  234000  189200  208500  65555523 -0.052273
2026-07-30  214000  226000  202000  207000  46694193 -0.007194
2026-07-31  257000  267000  243000  262500  58478873  0.268116

In [14]:
# df = fdr.DataReader('005930', '2026-07-01', '2026-08-01', exchange="KRX")
df = fdr.DataReader('KRX:005930', '2026-07-01', '2026-08-01')
df

'data_source' and 'exchange' argument deprecated, use in symbol like these:
  fdr.DataReader('FRED:DEXKOUS', '1990-01-01')
  fdr.DataReader('FRED:DEXKOUS')
  fdr.DataReader('FRED:NASDAQCOM,M2,HSN1F')

  fdr.DataReader('TSE:9984', '2020-01-01')
  fdr.DataReader('NYSE:CBOE', '1990-01-01')
  fdr.DataReader('SSE:000150', '1990-01-01')

              Open    High     Low   Close    Volume    Change
Date
2026-07-01  334500  339000  311500  314500  24968382 -0.058383
2026-07-02  290000  304000  281500  286000  38905074 -0.090620
2026-07-03  288500  313000  283500  309500  31520538  0.082168
2026-07-06  320000  325000  303000  318000  23872879  0.027464
2026-07-07  307000  310000  286000  296000  32421032 -0.069182
2026-07-08  285500  300000  273500  277500  33525758 -0.062500
2026-07-09  288500  291500  267500  278000  29703616  0.001802
2026-07-10  291000  298000  282000  285000  20088811  0.025180
2026-07-13  285000  292500  253000  254500  31882652 -0.107018
2026-07-14  255000  270000  247000  263000  40086496  0.033399
2026-07-15  283500  284500  273000  279500  24873414  0.062738
2026-07-16  264500  265500  252500  255000  27001478 -0.087657
2026-07-20  241000  257500  240000  244000  26804038 -0.043137
2026-07-21  247000  263500  243000  259000  20386896  0.061475
2026-07-22  276000  276000  260000  260500  22292003  0.005792
2026-07-23  269000  273000  263000  270000  16011816  0.036468
2026-07-24  266000  266500  247000  249500  26175580 -0.075926
2026-07-27  257000  258500  246000  254000  23296044  0.018036
2026-07-28  238500  240000  218500  220000  41639623 -0.133858
2026-07-29  226500  234000  189200  208500  65555523 -0.052273
2026-07-30  214000  226000  202000  207000  46694193 -0.007194
2026-07-31  257000  267000  243000  262500  58478873  0.268116

In [16]:
# '000150': 두산
df = fdr.DataReader('000150', '2026-07-01', '2026-08-01')
df

               Open     High      Low    Close  Volume    Change
Date
2026-07-01  1525000  1624000  1520000  1590000   79697  0.069267
2026-07-02  1523000  1549000  1402000  1447000   70915 -0.089937
2026-07-03  1456000  1457000  1324000  1433000   68056 -0.009675
2026-07-06  1441000  1503000  1356000  1410000   57981 -0.016050
2026-07-07  1410000  1410000  1242000  1320000   78654 -0.063830
2026-07-08  1260000  1351000  1220000  1268000   98470 -0.039394
2026-07-09  1285000  1318000  1160000  1203000  121708 -0.051262
2026-07-10  1250000  1445000  1233000  1382000  103119  0.148795
2026-07-13  1408000  1428000  1220000  1238000  100547 -0.104197
2026-07-14  1244000  1268000  1160000  1217000  208090 -0.016963
2026-07-15  1318000  1389000  1265000  1289000   61031  0.059162
2026-07-16  1268000  1268000  1184000  1202000   43531 -0.067494
2026-07-20  1187000  1189000  1101000  1119000   73920 -0.069052
2026-07-21  1120000  1185000  1066000  1123000   47941  0.003575
2026-07-22  1194000  1320000  1179000  1215000  100883  0.081923
2026-07-23  1249000  1317000  1232000  1276000   44194  0.050206
2026-07-24  1256000  1279000  1182000  1191000   46258 -0.066614
2026-07-27  1245000  1245000  1166000  1197000   34430  0.005038
2026-07-28  1129000  1196000  1023000  1046000  139994 -0.126149
2026-07-29  1078000  1128000   910000   999000   89968 -0.044933
2026-07-30   966000  1027000   889000   900000  107720 -0.099099
2026-07-31  1070000  1170000  1062000  1170000  134767  0.300000

In [23]:
df = fdr.DataReader('000150', '2026-07-01', '2026-08-01', exchange='SSE')
df

'data_source' and 'exchange' argument deprecated, use in symbol like these:
  fdr.DataReader('FRED:DEXKOUS', '1990-01-01')
  fdr.DataReader('FRED:DEXKOUS')
  fdr.DataReader('FRED:NASDAQCOM,M2,HSN1F')

  fdr.DataReader('TSE:9984', '2020-01-01')
  fdr.DataReader('NYSE:CBOE', '1990-01-01')
  fdr.DataReader('SSE:000150', '1990-01-01')

               Open     High      Low    Close  Volume    Change
Date
2026-07-01  1525000  1624000  1520000  1590000   79697  0.069267
2026-07-02  1523000  1549000  1402000  1447000   70915 -0.089937
2026-07-03  1456000  1457000  1324000  1433000   68056 -0.009675
2026-07-06  1441000  1503000  1356000  1410000   57981 -0.016050
2026-07-07  1410000  1410000  1242000  1320000   78654 -0.063830
2026-07-08  1260000  1351000  1220000  1268000   98470 -0.039394
2026-07-09  1285000  1318000  1160000  1203000  121708 -0.051262
2026-07-10  1250000  1445000  1233000  1382000  103119  0.148795
2026-07-13  1408000  1428000  1220000  1238000  100547 -0.104197
2026-07-14  1244000  1268000  1160000  1217000  208090 -0.016963
2026-07-15  1318000  1389000  1265000  1289000   61031  0.059162
2026-07-16  1268000  1268000  1184000  1202000   43531 -0.067494
2026-07-20  1187000  1189000  1101000  1119000   73920 -0.069052
2026-07-21  1120000  1185000  1066000  1123000   47941  0.003575
2026-07-22  1194000  1320000  1179000  1215000  100883  0.081923
2026-07-23  1249000  1317000  1232000  1276000   44194  0.050206
2026-07-24  1256000  1279000  1182000  1191000   46258 -0.066614
2026-07-27  1245000  1245000  1166000  1197000   34430  0.005038
2026-07-28  1129000  1196000  1023000  1046000  139994 -0.126149
2026-07-29  1078000  1128000   910000   999000   89968 -0.044933
2026-07-30   966000  1027000   889000   900000  107720 -0.099099
2026-07-31  1070000  1170000  1062000  1170000  134767  0.300000

In [21]:
# KOSPI index
df = fdr.DataReader('KS11', '2026-07-01', '2026-07-31')
df

,Close,UpDown,Comp,Change,Open,High,Low,Volume,Amount,MarCap
Date,,,,,,,,,,
2026-07-01,8303.41,2,-173.07,-0.0204,8591.50,8620.15,8143.33,468193407,39998686042470,6785431956394503
2026-07-02,7648.09,2,-655.32,-0.0789,7933.10,8136.28,7616.33,505157279,49900911277946,6251410554182236
2026-07-03,8088.34,1,440.25,0.0576,7739.75,8136.28,7378.10,465820788,45492055078817,6617011062826598
2026-07-06,8051.33,2,-37.01,-0.0046,8186.82,8327.26,7815.53,448691380,32002817887277,6591595226499214
2026-07-07,7656.31,2,-395.02,-0.0491,7919.20,7954.55,7389.22,516365835,40717402628437,6266412200628105
2026-07-08,7246.79,2,-409.52,-0.0535,7452.48,7791.66,7186.21,501070972,42465430925697,5931056230750011
2026-07-09,7291.91,1,45.12,0.0062,7486.64,7543.86,7063.76,582790735,39556657965016,5964859973661527
2026-07-10,7475.94,1,184.03,0.0252,7552.49,7704.93,7429.51,453242080,31576970770029,6118604296140554
2026-07-13,6806.93,2,-669.01,-0.0895,7412.03,7529.07,6783.43,474084812,40143819575662,5572485079774514
2026-07-14,6856.83,1,49.90,0.0073,6769.06,6979.92,6448.86,491599254,46697966573491,5616749703745019
2026-07-15,7284.41,1,427.58,0.0624,7082.91,7424.18,7082.91,397853705,34488295746773,5961100249061447
2026-07-16,6820.60,2,-463.81,-0.0637,6960.50,6995.93,6730.87,424279830,29820663017312,5576917784678867
2026-07-20,6516.27,2,-304.33,-0.0446,6643.58,6814.86,6472.80,345824614,29690576165881,5331388995510400
2026-07-21,6747.95,1,231.68,0.0356,6553.88,6836.86,6429.03,391091597,24810734536825,5525145833613097
2026-07-22,6797.70,1,49.75,0.0074,7052.09,7166.00,6791.06,373810110,28574069397052,5568155813322949
2026-07-23,7096.89,1,299.19,0.0440,6963.35,7108.44,6892.64,397345768,26856060831382,5814274124976124
2026-07-24,6690.62,2,-406.27,-0.0572,7000.78,7000.78,6650.41,397654875,30991958531519,5479519588763190
2026-07-27,6755.75,1,65.13,0.0097,6806.27,6806.27,6557.39,275717624,24294695707750,5533628393014013
2026-07-28,6023.66,2,-732.09,-0.1084,6400.27,6413.57,5992.91,331260982,36073927405132,4933296613154775
2026-07-29,5663.24,2,-360.42,-0.0598,6089.11,6228.52,5262.77,457384769,49217357151746,4669101404020380
2026-07-30,5593.56,2,-69.68,-0.0123,5681.77,5976.82,5547.41,378859389,38320902018593,4611484788421978
2026-07-31,6595.45,1,1001.89,0.1791,5657.79,6630.77,5629.76,434445151,49567650533548,5445193657915115

In [22]:
df = fdr.DataReader('USD/KRW', '2026-07-01', '2026-07-31')
df

,Open,High,Low,Close,Volume,Adj Close
2026-06-29,1542.420044,1554.709961,1542.420044,1541.729980,0,1541.729980
2026-06-30,1552.099976,1558.880005,1549.130005,1548.609985,0,1548.609985
2026-07-01,1551.400024,1556.530029,1537.189941,1551.810059,0,1551.810059
2026-07-02,1544.520020,1547.650024,1525.380005,1542.130005,0,1542.130005
2026-07-05,1531.579956,1536.550049,1526.140015,1531.000000,0,1531.000000
2026-07-06,1528.300049,1531.560059,1509.859985,1528.760010,0,1528.760010
2026-07-07,1521.050049,1521.209961,1498.959961,1519.859985,0,1519.859985
2026-07-08,1504.209961,1587.699951,1497.489990,1503.349976,0,1503.349976
2026-07-09,1507.099976,1512.719971,1499.150024,1505.910034,0,1505.910034
2026-07-12,1498.050049,1508.780029,1490.839966,1498.479980,0,1498.479980
2026-07-13,1498.030029,1499.079956,1485.060059,1497.699951,0,1497.699951
2026-07-14,1488.939941,1493.819946,1484.650024,1487.880005,0,1487.880005
2026-07-15,1486.150024,1488.800049,1476.369995,1486.199951,0,1486.199951
2026-07-16,1478.680054,1491.199951,1470.000000,1478.849976,0,1478.849976
2026-07-19,1487.699951,1489.300049,1477.089966,1487.390015,0,1487.390015
2026-07-20,1474.640015,1481.569946,1470.599976,1475.010010,0,1475.010010
2026-07-21,1479.910034,1484.199951,1475.099976,1479.719971,0,1479.719971
2026-07-22,1475.000000,1476.890015,1465.130005,1475.630005,0,1475.630005
2026-07-23,1474.569946,1474.699951,1458.150024,1474.040039,0,1474.040039
2026-07-26,1457.750000,1471.729980,1457.339966,1458.010010,0,1458.010010
2026-07-27,1466.920044,1470.969971,1452.219971,1464.439941,0,1464.439941
2026-07-28,1455.329956,1456.349976,1441.550049,1453.160034,0,1453.160034
2026-07-29,1441.770020,1447.459961,1417.930054,1442.280029,0,1442.280029

In [24]:
# symbol list
df = fdr.StockListing('KRX')
df

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,NaN,268000,3,0,0.00,275000,275500,266000,10739594,2902398900250,1566802666944000,5846278608,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,NaN,1637000,1,44000,2.76,1695000,1697000,1626000,2532112,4211114293000,1195816001505000,730492365,STK
2,005935,KR7005931001,삼성전자우,KOSPI,NaN,191000,1,3200,1.70,191600,194600,188100,2038558,390335759600,153252899773000,802371203,STK
3,402340,KR7402340004,SK스퀘어,KOSPI,NaN,1161000,1,44000,3.94,1182000,1183000,1130000,396823,457079457000,153203686146000,131958386,STK
4,009150,KR7009150004,삼성전기,KOSPI,NaN,1562000,1,59000,3.93,1593000,1600000,1511000,735943,1142287547000,116671553152000,74693696,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2867,279060,KR7279060008,이노벡스,KONEX,일반기업부,115,0,0,0.00,0,0,0,0,0,1127904590,9807866,KNX
2868,223220,KR7223220005,로지스몬,KONEX,일반기업부,162,5,-28,-14.74,162,191,162,7890,1278819,923872878,5702919,KNX
2869,002787,KR7002782001,진흥기업2우B,KOSPI,NaN,2895,0,0,0.00,0,0,0,0,0,853469160,294808,STK
2870,032685,KR7032681009,소프트센우,KOSDAQ,중견기업부,10860,4,2500,29.90,8270,10860,8270,10473,110478180,774991320,71362,KSQ
2871,327610,KR7327610002,펨토바이오메드,KONEX,일반기업부,75,1,24,47.06,44,75,40,48263,2530366,640206450,8536086,KNX