# 붓꽃(iris)의 품종 분류

In [1]:
# '꽃잎과 꽃받침의 크기' 를 기반으로 붓꽃의 품종 분류

# 데이터셋 : iris.csv   

# 컬럼
# SepalLength  (꽃받침의 길이)
# SepalWidth   (꽃받침의 폭)
# PetalLength  (꽃잎의 길이)
# PetalWidth   (꽃임이 너비)

# Name     품종명 (Species)⭐
#     "Iris-setosa", "Iris-versicolor", "Iris-virginica"  세가지 품종

# 출처 : https://www.kaggle.com/uciml/iris

In [2]:
# CSV 파일에는 약 150개의 데이터가 있는데,  
# 100개는 학습(train)을 위해 사용,   50개는 테스트(test)를 위해 사용

In [3]:
""" 
[수행 단계]

① 필요한 import 수행

② 데이터 읽어오기
   CSV -> DataFrame (변수명 df)
   기초 통계랑 확인
   
③ 입력데이터와 타겟데이터 분리
   입력데이터 →  변수명 data
   타겟데이터 →  변수명 target

④ train, test 세트 분리. 
   - 8:2로 분류 
   - 클래스별로 균등하게 분류되게 하고 

⑤ 전처리 (표준화)
   스케일러 객체 변수 → 변수명 scaler
  
⑥ 최적의 하이퍼 파라미터 찾기
   SVC 의 최적 하이퍼 파라미터 찾기 수행.  GridSearchCV 사용

   param_grid = {'C': [0.1, 1, 10, 100],               
              'gamma': [0.001, 0.1, 1, 10, 100], 
              'kernel': ['linear', 'rbf']}

   최적의 모델 저장 -> 변수명 clf

⑦ test 점수 확인
    
⑧ 다른 평가지표들 확인

⑨ 예측 동작 확인

⑩ 모델 & 스케일러 저장하기
   모델 -> 파일명 iris_model.pkl
   스케일러 -> 파일명 iris_scaler.pkl

   (위 저장 정보는 웹 애플리케이션에서 사용될것임)

⑪ 저장된 모델 & 스케일러 불러오기

⑫ 예측 함수 만들어 보고 동작 시키기

    # 예측 함수 작성
    # 입력값: 웹에서 사용자가 입력한 값
    # 출력값: 분류 문자열 (ex: Iris-setosa, Iris-versicolor, Iris-virginica)
    def predict_iris(sepal_length, sepal_width, petal_length, petal_width) -> str:


★ 각 수행 단계별로 적절한 제목으로 작성
★ 각 수행 단계마다 이 단계가 무엇을 하는 단계이고, 사용하는 파라미터와
   (필요한 경우) 어떠한 입력으로 어떠한 결과가 나오는지 확인하고 설명을 남기기
★ 각 단계마다 내가 무엇을 확인했는지 코드와 함께 설명 남기기
"""
None

# ① 필요한 import 수행

In [45]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn import svm, metrics
import joblib   # 학습 모델 저장  pip install joblib
import glob, os, re, json

import pandas as pd

# ② 데이터 읽어오기
   CSV -> DataFrame (변수명 df)
   기초 통계랑 확인

In [46]:
df = pd.read_csv(os.path.join('.', 'iris.csv'))
df

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [47]:
df.shape

(150, 5)

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SepalLength  150 non-null    float64
 1   SepalWidth   150 non-null    float64
 2   PetalLength  150 non-null    float64
 3   PetalWidth   150 non-null    float64
 4   Name         150 non-null    str
dtypes: float64(4), str(1)
memory usage: 7.9 KB

In [49]:
df.describe()

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [50]:
df.Name.unique()

<ArrowStringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

# ③ 입력데이터와 타겟데이터 분리
   입력데이터 →  변수명 data
   타겟데이터 →  변수명 target

In [51]:
data = df[['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']]

print(data.shape)
data[:5]

(150, 4)

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [52]:
target = df['Name']

print(target.shape)
target

(150,)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Name, Length: 150, dtype: str

# ④ train, test 세트 분리. 
   - 8:2로 분류 
   - 클래스별로 균등하게 분류되게 하고

In [54]:
X_train, X_test, y_train, y_test = \
    train_test_split(data, target, test_size=0.2, stratify=target, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [55]:
y_train.value_counts()

Name
Iris-setosa        40
Iris-virginica     40
Iris-versicolor    40
Name: count, dtype: int64

In [56]:
y_test.value_counts()

Name
Iris-setosa        10
Iris-virginica     10
Iris-versicolor    10
Name: count, dtype: int64

# ⑤ 전처리 (표준화)
   스케일러 객체 변수 → 변수명 scaler

In [57]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train[:5])
print()
print(X_train_scaled[:5])

     SepalLength  SepalWidth  PetalLength  PetalWidth
8            4.4         2.9          1.4         0.2
106          4.9         2.5          4.5         1.7
76           6.8         2.8          4.8         1.4
9            4.9         3.1          1.5         0.1
89           5.5         2.5          4.0         1.3

[[-1.72156775 -0.32483982 -1.34703555 -1.32016847]
 [-1.12449223 -1.22612948  0.41429037  0.65186742]
 [ 1.14439475 -0.55016223  0.58474127  0.25746024]
 [-1.12449223  0.12580502 -1.29021859 -1.45163753]
 [-0.40800161 -1.22612948  0.13020555  0.12599118]]

In [58]:
pd.DataFrame(data=X_train_scaled).describe()

                  0             1             2             3
count  1.200000e+02  1.200000e+02  1.200000e+02  1.200000e+02
mean  -1.369275e-16  4.551914e-16 -9.066821e-17  5.366078e-17
std    1.004193e+00  1.004193e+00  1.004193e+00  1.004193e+00
min   -1.840983e+00 -2.352742e+00 -1.517486e+00 -1.451638e+00
25%   -8.856620e-01 -5.501622e-01 -1.233402e+00 -1.188699e+00
50%   -1.094638e-01 -9.951740e-02  2.722480e-01  1.259912e-01
75%    6.667343e-01  5.764498e-01  7.551922e-01  7.833365e-01
max    2.457961e+00  3.054996e+00  1.777898e+00  1.703620e+00

# ⑥ 최적의 하이퍼 파라미터 찾기
   SVC 의 최적 하이퍼 파라미터 찾기 수행.  GridSearchCV 사용

   param_grid = {'C': [0.1, 1, 10, 100],               
              'gamma': [0.001, 0.1, 1, 10, 100], 
              'kernel': ['linear', 'rbf']}

   최적의 모델 저장 -> 변수명 clf

In [59]:
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [0.001, 0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf'],
}

gs = GridSearchCV(
    svm.SVC(random_state=42),
    param_grid,
    n_jobs=-1,
    cv=5,
)

gs.fit(X_train_scaled, y_train)

GridSearchCV(cv=5, estimator=SVC(random_state=42), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [0.001, 0.1, 1, 10, 100],
                         'kernel': ['linear', 'rbf']})

In [60]:
print("최적 점수 : {}".format(gs.best_score_))
print("최적 파라미터 : {}".format(gs.best_params_))

최적 점수 : 0.9833333333333332
최적 파라미터 : {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}

In [61]:
# 최적의 모델 저장
clf = gs.best_estimator_
clf

SVC(C=1, gamma=0.1, random_state=42)

In [62]:
pd.DataFrame(gs.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.036732,0.013681,0.003044,0.001720,0.1,0.001,linear,"{'C': 0.1, 'gamma': 0.001, 'kernel': 'linear'}",0.916667,1.000000,1.000000,0.958333,1.000000,0.975000,0.033333,2
1,0.024868,0.025287,0.002687,0.001734,0.1,0.001,rbf,"{'C': 0.1, 'gamma': 0.001, 'kernel': 'rbf'}",0.875000,0.875000,0.833333,0.875000,0.875000,0.866667,0.016667,34
2,0.002700,0.001181,0.001651,0.001167,0.1,0.100,linear,"{'C': 0.1, 'gamma': 0.1, 'kernel': 'linear'}",0.916667,1.000000,1.000000,0.958333,1.000000,0.975000,0.033333,2
3,0.002754,0.000589,0.001318,0.000636,0.1,0.100,rbf,"{'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}",0.875000,0.875000,0.833333,0.875000,0.916667,0.875000,0.026352,30
4,0.001414,0.000517,0.000626,0.000253,0.1,1.000,linear,"{'C': 0.1, 'gamma': 1, 'kernel': 'linear'}",0.916667,1.000000,1.000000,0.958333,1.000000,0.975000,0.033333,2
5,0.001557,0.000469,0.000907,0.000393,0.1,1.000,rbf,"{'C': 0.1, 'gamma': 1, 'kernel': 'rbf'}",0.916667,0.875000,0.958333,0.916667,0.958333,0.925000,0.031180,28
6,0.001785,0.000188,0.000821,0.000269,0.1,10.000,linear,"{'C': 0.1, 'gamma': 10, 'kernel': 'linear'}",0.916667,1.000000,1.000000,0.958333,1.000000,0.975000,0.033333,2
7,0.001533,0.000499,0.000712,0.000253,0.1,10.000,rbf,"{'C': 0.1, 'gamma': 10, 'kernel': 'rbf'}",0.750000,0.666667,0.791667,0.666667,0.833333,0.741667,0.066667,36
8,0.001087,0.000105,0.000476,0.000015,0.1,100.000,linear,"{'C': 0.1, 'gamma': 100, 'kernel': 'linear'}",0.916667,1.000000,1.000000,0.958333,1.000000,0.975000,0.033333,2
9,0.001554,0.000598,0.000722,0.000312,0.1,100.000,rbf,"{'C': 0.1, 'gamma': 100, 'kernel': 'rbf'}",0.375000,0.333333,0.333333,0.375000,0.375000,0.358333,0.020412,40
10,0.001797,0.000441,0.001431,0.000477,1.0,0.001,linear,"{'C': 1, 'gamma': 0.001, 'kernel': 'linear'}",0.958333,0.958333,0.958333,1.000000,1.000000,0.975000,0.020412,2
11,0.000992,0.000233,0.000554,0.000091,1.0,0.001,rbf,"{'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}",0.875000,0.875000,0.833333,0.875000,0.875000,0.866667,0.016667,34
12,0.000929,0.000208,0.000530,0.000158,1.0,0.100,linear,"{'C': 1, 'gamma': 0.1, 'kernel': 'linear'}",0.958333,0.958333,0.958333,1.000000,1.000000,0.975000,0.020412,2
13,0.000931,0.000166,0.000496,0.000086,1.0,0.100,rbf,"{'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}",0.916667,1.000000,1.000000,1.000000,1.000000,0.983333,0.033333,1
14,0.000755,0.000111,0.000412,0.000023,1.0,1.000,linear,"{'C': 1, 'gamma': 1, 'kernel': 'linear'}",0.958333,0.958333,0.958333,1.000000,1.000000,0.975000,0.020412,2
15,0.000788,0.000089,0.000454,0.000049,1.0,1.000,rbf,"{'C': 1, 'gamma': 1, 'kernel': 'rbf'}",0.916667,1.000000,0.916667,0.958333,1.000000,0.958333,0.037268,25
16,0.000669,0.000089,0.000397,0.000025,1.0,10.000,linear,"{'C': 1, 'gamma': 10, 'kernel': 'linear'}",0.958333,0.958333,0.958333,1.000000,1.000000,0.975000,0.020412,2
17,0.000854,0.000111,0.000471,0.000053,1.0,10.000,rbf,"{'C': 1, 'gamma': 10, 'kernel': 'rbf'}",0.875000,0.875000,0.916667,0.791667,0.916667,0.875000,0.045644,30
18,0.001140,0.000486,0.000756,0.000323,1.0,100.000,linear,"{'C': 1, 'gamma': 100, 'kernel': 'linear'}",0.958333,0.958333,0.958333,1.000000,1.000000,0.975000,0.020412,2
19,0.000836,0.000076,0.000632,0.000336,1.0,100.000,rbf,"{'C': 1, 'gamma': 100, 'kernel': 'rbf'}",0.458333,0.416667,0.458333,0.416667,0.541667,0.458333,0.045644,39
20,0.001168,0.000582,0.000655,0.000466,10.0,0.001,linear,"{'C': 10, 'gamma': 0.001, 'kernel': 'linear'}",0.875000,0.958333,0.958333,1.000000,1.000000,0.958333,0.045644,20
21,0.000963,0.000502,0.000496,0.000085,10.0,0.001,rbf,"{'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}",0.916667,0.916667,0.833333,0.916667,0.916667,0.900000,0.033333,29
22,0.000923,0.000227,0.000567,0.000214,10.0,0.100,linear,"{'C': 10, 'gamma': 0.1, 'kernel': 'linear'}",0.875000,0.958333,0.958333,1.000000,1.000000,0.958333,0.045644,20
23,0.000706,0.000058,0.000654,0.000259,10.0,0.100,rbf,"{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}",0.958333,0.958333,0.958333,0.958333,1.000000,0.966667,0.016667,13
24,0.000889,0.000485,0.000408,0.000056,10.0,1.000,linear,"{'C': 10, 'gamma': 1, 'kernel': 'linear'}",0.875000,0.958333,0.958333,1.000000,1.000000,0.958333,0.045644,20
25,0.001017,0.000393,0.000540,0.000224,10.0,1.000,rbf,"{'C': 10, 'gamma': 1, 'kernel': 'rbf'}",0.916667,0.958333,0.916667,0.958333,1.000000,0.950000,0.031180,26
26,0.000751,0.000274,0.000441,0.000101,10.0,10.000,linear,"{'C': 10, 'gamma': 10, 'kernel': 'linear'}",0.875000,0.958333,0.958333,1.000000,1.000000,0.958333,0.045644,20
27,0.000750,0.000065,0.000444,0.000063,10.0,10.000,rbf,"{'C': 10, 'gamma': 10, 'kernel': 'rbf'}",0.875000,0.875000,0.916667,0.791667,0.916667,0.875000,0.045644,30
28,0.000765,0.000172,0.000401,0.000028,10.0,100.000,linear,"{'C': 10, 'gamma': 100, 'kernel': 'linear'}",0.875000,0.958333,0.958333,1.000000,1.000000,0.958333,0.045644,20
29,0.001051,0.000400,0.000480,0.000043,10.0,100.000,rbf,"{'C': 10, 'gamma': 100, 'kernel': 'rbf'}",0.458333,0.416667,0.541667,0.416667,0.541667,0.475000,0.056519,37
30,0.000808,0.000122,0.000424,0.000035,100.0,0.001,linear,"{'C': 100, 'gamma': 0.001, 'kernel': 'linear'}",0.958333,0.958333,0.958333,0.958333,1.000000,0.966667,0.016667,13
31,0.000755,0.000031,0.000442,0.000012,100.0,0.001,rbf,"{'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}",0.916667,1.000000,0.958333,1.000000,1.000000,0.975000,0.033333,2
32,0.001014,0.000229,0.000451,0.000031,100.0,0.100,linear,"{'C': 100, 'gamma': 0.1, 'kernel': 'linear'}",0.958333,0.958333,0.958333,0.958333,1.000000,0.966667,0.016667,13
33,0.000820,0.000040,0.000449,0.000014,100.0,0.100,rbf,"{'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}",0.958333,0.958333,0.958333,0.958333,1.000000,0.966667,0.016667,13
34,0.000876,0.000156,0.000519,0.000161,100.0,1.000,linear,"{'C': 100, 'gamma': 1, 'kernel': 'linear'}",0.958333,0.958333,0.958333,0.958333,1.000000,0.966667,0.016667,13
35,0.000938,0.000055,0.000462,0.000014,100.0,1.000,rbf,"{'C': 100, 'gamma': 1, 'kernel': 'rbf'}",0.916667,0.958333,0.916667,0.958333,1.000000,0.950000,0.031180,26
36,0.000877,0.000125,0.000472,0.000072,100.0,10.000,linear,"{'C': 100, 'gamma': 10, 'kernel': 'linear'}",0.958333,0.958333,0.958333,0.958333,1.000000,0.966667,0.016667,13
37,0.001166,0.000162,0.000540,0.000044,100.0,10.000,rbf,"{'C': 100, 'gamma': 10, 'kernel': 'rbf'}",0.875000,0.875000,0.916667,0.791667,0.916667,0.875000,0.045644,30
38,0.001075,0.000180,0.000478,0.000039,100.0,100.000,linear,"{'C': 100, 'gamma': 100, 'kernel': 'linear'}",0.958333,0.958333,0.958333,0.958333,1.000000,0.966667,0.016667,13
39,0.001094,0.000099,0.000505,0.000015,100.0,100.000,rbf,"{'C': 100, 'gamma': 100, 'kernel': 'rbf'}",0.458333,0.416667,0.541667,0.416667,0.541667,0.475000,0.056519,37

In [63]:
print(gs.cv_results_['mean_test_score'])

[0.975      0.86666667 0.975      0.875      0.975      0.925
 0.975      0.74166667 0.975      0.35833333 0.975      0.86666667
 0.975      0.98333333 0.975      0.95833333 0.975      0.875
 0.975      0.45833333 0.95833333 0.9        0.95833333 0.96666667
 0.95833333 0.95       0.95833333 0.875      0.95833333 0.475
 0.96666667 0.975      0.96666667 0.96666667 0.96666667 0.95
 0.96666667 0.875      0.96666667 0.475     ]

# ⑦ test 점수 확인

In [65]:
print(clf.score(X_train_scaled, y_train))
print(clf.score(X_test_scaled, y_test))

0.9833333333333333
0.9666666666666667

# ⑧ 다른 평가지표들 확인

In [66]:
predict = clf.predict(X_test_scaled)

print(predict)
print(y_test.values)

['Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa']
<ArrowStringArray>
[    'Iris-setosa',  'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
     'Iris-setosa', 'Iris-versicolor',     'Iris-setosa',     'Iris-setosa',
  'Iris-virginica', 'Iris-versicolor',  'Iris-virginica',  'Iris-virginica',
  'Iris-virginica', 'Iris-versicolor',     'Iris-setosa',     'Iris-setosa',
     'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',  'Iris-virginica',
     'Iris-setosa',  'Iris-virginica', 'Iris-versicolor',  'Iris-virginica',
  'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',     'Iris-setosa',
  'Iris-virginica',     'Iris-setosa']
Length: 30, dtype: str

In [67]:
ac_score = metrics.accuracy_score(y_test, predict)
cl_report =  metrics.classification_report(y_test, predict)
print("정답룰 =", ac_score)
print("리포트 =\n", cl_report)

정답룰 = 0.9666666666666667
리포트 =
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.90      0.95        10
 Iris-virginica       0.91      1.00      0.95        10

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

# ⑨ 예측 동작 확인

In [68]:
print(clf.predict(scaler.transform(pd.DataFrame(
    [[5.4, 3.3, 1.4, 0.2]],
    columns=['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth'],
))))

['Iris-setosa']

# ⑩ 모델 & 스케일러 저장하기
   모델 -> 파일명 iris_model.pkl
   스케일러 -> 파일명 iris_scaler.pkl

   (위 저장 정보는 웹 애플리케이션에서 사용될것임)

In [69]:
model_path = os.path.join('.', r'iris_model.pkl')
joblib.dump(clf, model_path)

['./iris_model.pkl']

In [70]:
model_path = os.path.join('.', r'iris_scaler.pkl')
joblib.dump(scaler, model_path)

['./iris_scaler.pkl']

# ⑪ 저장된 모델 & 스케일러 불러오기

In [71]:
model_path = os.path.join('.', r'iris_model.pkl')
clf = joblib.load(model_path)
clf

SVC(C=1, gamma=0.1, random_state=42)

In [72]:
model_path = os.path.join('.', r'iris_scaler.pkl')
scaler = joblib.load(model_path)
scaler

StandardScaler()

# ⑫ 예측 함수 만들어 보고 동작 시키기

In [73]:
def predict_iris(sepal_length, sepal_width, petal_length, petal_width):
    iris = pd.DataFrame(
        [[sepal_length, sepal_width, petal_length, petal_width]],
        columns=['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth'],
    )

    X_scaled = scaler.transform(iris)

    result = clf.predict(X_scaled)

    return result[0]

In [74]:
print(predict_iris(5.4, 3.3, 1.4, 0.2))

Iris-setosa